//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RePKG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RePKG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Copying: {0}.
        /// </summary>
        internal static string CopyingFileName {
            get {
                return ResourceManager.GetString("CopyingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Decompiling: {0}.
        /// </summary>
        internal static string DecompilingName {
            get {
                return ResourceManager.GetString("DecompilingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Extracting: {0}.
        /// </summary>
        internal static string ExtractingName {
            get {
                return ResourceManager.GetString("ExtractingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///### Extracting package: {0}.
        /// </summary>
        internal static string ExtractingPackage {
            get {
                return ResourceManager.GetString("ExtractingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///### Extracting texture: {0}.
        /// </summary>
        internal static string ExtractingTexture {
            get {
                return ResourceManager.GetString("ExtractingTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decompile.
        /// </summary>
        internal static string FailedToDecompile {
            get {
                return ResourceManager.GetString("FailedToDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file does not have an extension .pkg/.tex required.
        /// </summary>
        internal static string FileExtensionNotFound {
            get {
                return ResourceManager.GetString("FileExtensionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info about package {0}.
        /// </summary>
        internal static string InfoAboutPackage {
            get {
                return ResourceManager.GetString("InfoAboutPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file not found.
        /// </summary>
        internal static string InputFileNotFound {
            get {
                return ResourceManager.GetString("InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file/directory doesn&apos;t exist!.
        /// </summary>
        internal static string InputNotFound {
            get {
                return ResourceManager.GetString("InputNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory: {0}.
        /// </summary>
        internal static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package entries:.
        /// </summary>
        internal static string PackageEntries {
            get {
                return ResourceManager.GetString("PackageEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Skipping, already exists: {0}.
        /// </summary>
        internal static string SkippingAlreadyExists {
            get {
                return ResourceManager.GetString("SkippingAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminating....
        /// </summary>
        internal static string Terminating {
            get {
                return ResourceManager.GetString("Terminating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized file extension: {0}.
        /// </summary>
        internal static string UnrecognizedFileExtension {
            get {
                return ResourceManager.GetString("UnrecognizedFileExtension", resourceCulture);
            }
        }
    }
}
